%% -*- mode: octave; -*-

%% Elements (Extra)

%% Author: Edgar Gonzàlez i Pellicer


%%%%%%%%%%%%%%%%
%% Clusterers %%
%%%%%%%%%%%%%%%%

%% Objects
clusterer_kmeans = ...
    struct("make", @(dist, extra) ...
	   KMeans(dist, struct("max_iterations",   str2double(extra{1}), ...
			       "change_threshold", str2double(extra{2}))));

clusterer_rproj = ...
    struct("make", @(dist, extra) ...
	   RandomProj(struct("soft_alpha", str2double(extra{1}))));

clusterer_rand = ...
    struct("make", @(dist, extra) ...
	   Random(struct("concentration", str2double(extra{1}))));

clusterer_voro = ...
    struct("make", @(dist, extra) ...
	   Voronoi(dist, struct("soft_alpha", str2double(extra{1}))));

%% Index
clusterers = ...
    struct("kmeans", clusterer_kmeans, ...
	   "rand",   clusterer_rand, ...
	   "rproj",  clusterer_rproj, ...
	   "voro",   clusterer_voro);
