% Test for get_options.m

% Author: Edgar Gonzalez

[ args, opts ] = get_options("simple",     "simple", ...
			     "negable!",   "negable", ...
			     "pseudo~",    "simple", ...
			     "negated-",   "simple", ...
			     "integer=i",  "integer", ...
			     "float=f",    "float", ...
			     "string=s",   "string", ...
			     "radio1=r1", "radio", ...
			     "radio2=r2", "radio", ...
			     "radio3=r3", "radio", ...
			     "radio4=r4", "radio")

% Local Variables:
% mode:octave
% End:
