%% -*- mode: octave; -*-

%% Add something to the LOADPATH
addpath("/home/usuaris/egonzalez/devel/research/matlabClustering/aux", ...
	"/home/usuaris/egonzalez/devel/research/matlabClustering/io",  ...
	"/home/usuaris/egonzalez/devel/research/matlabClustering/combination", ...
	"/home/usuaris/egonzalez/devel/research/matlabClustering/measures", ...
	"/home/usuaris/egonzalez/devel/research/matlabClustering/weak");
